/**
 * List of timezones supported by WhatsApp
 */
// export const WHATSAPP_TIMEZONES = [
//   { name: 'Africa/Abidjan (GMT+0)', value: 'Africa/Abidjan' },
//   { name: 'Africa/Accra (GMT+0)', value: 'Africa/Accra' },
//   { name: 'Africa/Addis_Ababa (GMT+3)', value: 'Africa/Addis_Ababa' },
//   { name: 'Africa/Algiers (GMT+1)', value: 'Africa/Algiers' },
//   { name: 'Africa/Cairo (GMT+2)', value: 'Africa/Cairo' },
//   { name: 'Africa/Casablanca (GMT+1)', value: 'Africa/Casablanca' },
//   { name: 'Africa/Johannesburg (GMT+2)', value: 'Africa/Johannesburg' },
//   { name: 'Africa/Lagos (GMT+1)', value: 'Africa/Lagos' },
//   { name: 'Africa/Nairobi (GMT+3)', value: 'Africa/Nairobi' },
//   { name: 'Africa/Tunis (GMT+1)', value: 'Africa/Tunis' },
//   { name: 'America/Anchorage (GMT-8)', value: 'America/Anchorage' },
//   { name: 'America/Argentina/Buenos_Aires (GMT-3)', value: 'America/Argentina/Buenos_Aires' },
//   { name: 'America/Bogota (GMT-5)', value: 'America/Bogota' },
//   { name: 'America/Chicago (GMT-5)', value: 'America/Chicago' },
//   { name: 'America/Denver (GMT-6)', value: 'America/Denver' },
//   { name: 'America/Guatemala (GMT-6)', value: 'America/Guatemala' },
//   { name: 'America/Halifax (GMT-3)', value: 'America/Halifax' },
//   { name: 'America/La_Paz (GMT-4)', value: 'America/La_Paz' },
//   { name: 'America/Lima (GMT-5)', value: 'America/Lima' },
//   { name: 'America/Los_Angeles (GMT-7)', value: 'America/Los_Angeles' },
//   { name: 'America/Mexico_City (GMT-5)', value: 'America/Mexico_City' },
//   { name: 'America/New_York (GMT-4)', value: 'America/New_York' },
//   { name: 'America/Panama (GMT-5)', value: 'America/Panama' },
//   { name: 'America/Phoenix (GMT-7)', value: 'America/Phoenix' },
//   { name: 'America/Santiago (GMT-4)', value: 'America/Santiago' },
//   { name: 'America/Sao_Paulo (GMT-3)', value: 'America/Sao_Paulo' },
//   { name: 'America/St_Johns (GMT-2:30)', value: 'America/St_Johns' },
//   { name: 'America/Toronto (GMT-4)', value: 'America/Toronto' },
//   { name: 'Asia/Baku (GMT+4)', value: 'Asia/Baku' },
//   { name: 'Asia/Bangkok (GMT+7)', value: 'Asia/Bangkok' },
//   { name: 'Asia/Dhaka (GMT+6)', value: 'Asia/Dhaka' },
//   { name: 'Asia/Dubai (GMT+4)', value: 'Asia/Dubai' },
//   { name: 'Asia/Hong_Kong (GMT+8)', value: 'Asia/Hong_Kong' },
//   { name: 'Asia/Istanbul (GMT+3)', value: 'Asia/Istanbul' },
//   { name: 'Asia/Jakarta (GMT+7)', value: 'Asia/Jakarta' },
//   { name: 'Asia/Jerusalem (GMT+3)', value: 'Asia/Jerusalem' },
//   { name: 'Asia/Karachi (GMT+5)', value: 'Asia/Karachi' },
//   { name: 'Asia/Kolkata (GMT+5:30)', value: 'Asia/Kolkata' },
//   { name: 'Asia/Kuala_Lumpur (GMT+8)', value: 'Asia/Kuala_Lumpur' },
//   { name: 'Asia/Manila (GMT+8)', value: 'Asia/Manila' },
//   { name: 'Asia/Qatar (GMT+3)', value: 'Asia/Qatar' },
//   { name: 'Asia/Riyadh (GMT+3)', value: 'Asia/Riyadh' },
//   { name: 'Asia/Seoul (GMT+9)', value: 'Asia/Seoul' },
//   { name: 'Asia/Shanghai (GMT+8)', value: 'Asia/Shanghai' },
//   { name: 'Asia/Singapore (GMT+8)', value: 'Asia/Singapore' },
//   { name: 'Asia/Taipei (GMT+8)', value: 'Asia/Taipei' },
//   { name: 'Asia/Tokyo (GMT+9)', value: 'Asia/Tokyo' },
//   { name: 'Australia/Adelaide (GMT+9:30)', value: 'Australia/Adelaide' },
//   { name: 'Australia/Brisbane (GMT+10)', value: 'Australia/Brisbane' },
//   { name: 'Australia/Darwin (GMT+9:30)', value: 'Australia/Darwin' },
//   { name: 'Australia/Melbourne (GMT+10)', value: 'Australia/Melbourne' },
//   { name: 'Australia/Perth (GMT+8)', value: 'Australia/Perth' },
//   { name: 'Australia/Sydney (GMT+10)', value: 'Australia/Sydney' },
//   { name: 'Europe/Amsterdam (GMT+2)', value: 'Europe/Amsterdam' },
//   { name: 'Europe/Athens (GMT+3)', value: 'Europe/Athens' },
//   { name: 'Europe/Berlin (GMT+2)', value: 'Europe/Berlin' },
//   { name: 'Europe/Brussels (GMT+2)', value: 'Europe/Brussels' },
//   { name: 'Europe/Budapest (GMT+2)', value: 'Europe/Budapest' },
//   { name: 'Europe/Copenhagen (GMT+2)', value: 'Europe/Copenhagen' },
//   { name: 'Europe/Dublin (GMT+1)', value: 'Europe/Dublin' },
//   { name: 'Europe/Helsinki (GMT+3)', value: 'Europe/Helsinki' },
//   { name: 'Europe/Lisbon (GMT+1)', value: 'Europe/Lisbon' },
//   { name: 'Europe/London (GMT+1)', value: 'Europe/London' },
//   { name: 'Europe/Madrid (GMT+2)', value: 'Europe/Madrid' },
//   { name: 'Europe/Moscow (GMT+3)', value: 'Europe/Moscow' },
//   { name: 'Europe/Oslo (GMT+2)', value: 'Europe/Oslo' },
//   { name: 'Europe/Paris (GMT+2)', value: 'Europe/Paris' },
//   { name: 'Europe/Prague (GMT+2)', value: 'Europe/Prague' },
//   { name: 'Europe/Rome (GMT+2)', value: 'Europe/Rome' },
//   { name: 'Europe/Stockholm (GMT+2)', value: 'Europe/Stockholm' },
//   { name: 'Europe/Vienna (GMT+2)', value: 'Europe/Vienna' },
//   { name: 'Europe/Warsaw (GMT+2)', value: 'Europe/Warsaw' },
//   { name: 'Europe/Zurich (GMT+2)', value: 'Europe/Zurich' },
//   { name: 'Pacific/Auckland (GMT+12)', value: 'Pacific/Auckland' },
//   { name: 'Pacific/Honolulu (GMT-10)', value: 'Pacific/Honolulu' },
//   { name: 'UTC (GMT+0)', value: 'UTC' }
// ]; 

export const WHATSAPP_TIMEZONES = [
  { name: 'Pacific/Niue (GMT-11)', value: 'Pacific/Niue' },
  { name: 'Pacific/Pago_Pago (GMT-11)', value: 'Pacific/Pago_Pago' },
  { name: 'Pacific/Honolulu (GMT-10)', value: 'Pacific/Honolulu' },
  { name: 'Pacific/Tahiti (GMT-10)', value: 'Pacific/Tahiti' },
  { name: 'Pacific/Marquesas (GMT-9:30)', value: 'Pacific/Marquesas' },
  { name: 'America/Anchorage (GMT-9)', value: 'America/Anchorage' },
  { name: 'Pacific/Gambier (GMT-9)', value: 'Pacific/Gambier' },
  { name: 'America/Los_Angeles (GMT-8)', value: 'America/Los_Angeles' },
  { name: 'America/Vancouver (GMT-8)', value: 'America/Vancouver' },
  { name: 'America/Denver (GMT-7)', value: 'America/Denver' },
  { name: 'America/Phoenix (GMT-7)', value: 'America/Phoenix' },
  { name: 'America/Chicago (GMT-6)', value: 'America/Chicago' },
  { name: 'America/Mexico_City (GMT-6)', value: 'America/Mexico_City' },
  { name: 'America/New_York (GMT-5)', value: 'America/New_York' },
  { name: 'America/Toronto (GMT-5)', value: 'America/Toronto' },
  { name: 'America/Halifax (GMT-4)', value: 'America/Halifax' },
  { name: 'America/Caracas (GMT-4)', value: 'America/Caracas' },
  { name: 'America/St_Johns (GMT-3:30)', value: 'America/St_Johns' },
  { name: 'America/Sao_Paulo (GMT-3)', value: 'America/Sao_Paulo' },
  { name: 'America/Argentina/Buenos_Aires (GMT-3)', value: 'America/Argentina/Buenos_Aires' },
  { name: 'Atlantic/South_Georgia (GMT-2)', value: 'Atlantic/South_Georgia' },
  { name: 'Atlantic/Azores (GMT-1)', value: 'Atlantic/Azores' },
  { name: 'Europe/London (GMT+0)', value: 'Europe/London' },
  { name: 'Africa/Casablanca (GMT+0)', value: 'Africa/Casablanca' },
  { name: 'Europe/Paris (GMT+1)', value: 'Europe/Paris' },
  { name: 'Europe/Berlin (GMT+1)', value: 'Europe/Berlin' },
  { name: 'Europe/Athens (GMT+2)', value: 'Europe/Athens' },
  { name: 'Africa/Cairo (GMT+2)', value: 'Africa/Cairo' },
  { name: 'Europe/Moscow (GMT+3)', value: 'Europe/Moscow' },
  { name: 'Africa/Nairobi (GMT+3)', value: 'Africa/Nairobi' },
  { name: 'Asia/Tehran (GMT+3:30)', value: 'Asia/Tehran' },
  { name: 'Asia/Dubai (GMT+4)', value: 'Asia/Dubai' },
  { name: 'Europe/Samara (GMT+4)', value: 'Europe/Samara' },
  { name: 'Asia/Kabul (GMT+4:30)', value: 'Asia/Kabul' },
  { name: 'Asia/Karachi (GMT+5)', value: 'Asia/Karachi' },
  { name: 'Asia/Tashkent (GMT+5)', value: 'Asia/Tashkent' },
  { name: 'Asia/Kolkata (GMT+5:30)', value: 'Asia/Kolkata' },
  { name: 'Asia/Kathmandu (GMT+5:45)', value: 'Asia/Kathmandu' },
  { name: 'Asia/Dhaka (GMT+6)', value: 'Asia/Dhaka' },
  { name: 'Asia/Almaty (GMT+6)', value: 'Asia/Almaty' },
  { name: 'Asia/Yangon (GMT+6:30)', value: 'Asia/Yangon' },
  { name: 'Asia/Bangkok (GMT+7)', value: 'Asia/Bangkok' },
  { name: 'Asia/Jakarta (GMT+7)', value: 'Asia/Jakarta' },
  { name: 'Asia/Shanghai (GMT+8)', value: 'Asia/Shanghai' },
  { name: 'Asia/Singapore (GMT+8)', value: 'Asia/Singapore' },
  { name: 'Asia/Tokyo (GMT+9)', value: 'Asia/Tokyo' },
  { name: 'Asia/Seoul (GMT+9)', value: 'Asia/Seoul' },
  { name: 'Australia/Adelaide (GMT+9:30)', value: 'Australia/Adelaide' },
  { name: 'Australia/Darwin (GMT+9:30)', value: 'Australia/Darwin' },
  { name: 'Australia/Sydney (GMT+10)', value: 'Australia/Sydney' },
  { name: 'Pacific/Port_Moresby (GMT+10)', value: 'Pacific/Port_Moresby' },
  { name: 'Australia/Lord_Howe (GMT+10:30)', value: 'Australia/Lord_Howe' },
  { name: 'Pacific/Noumea (GMT+11)', value: 'Pacific/Noumea' },
  { name: 'Asia/Vladivostok (GMT+11)', value: 'Asia/Vladivostok' },
  { name: 'Pacific/Auckland (GMT+12)', value: 'Pacific/Auckland' },
  { name: 'Pacific/Fiji (GMT+12)', value: 'Pacific/Fiji' },
  { name: 'Pacific/Chatham (GMT+12:45)', value: 'Pacific/Chatham' },
  { name: 'Pacific/Tongatapu (GMT+13)', value: 'Pacific/Tongatapu' },
  { name: 'Pacific/Apia (GMT+13)', value: 'Pacific/Apia' },
  { name: 'Pacific/Kiritimati (GMT+14)', value: 'Pacific/Kiritimati' }
];